version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/Savvy-Saver
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./db.sqlite3:/Savvy-Saver/db.sqlite3
